//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbulanceCardLogs
    {
        public int Id { get; set; }
        public int AmbulanceCardId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Directory { get; set; }
        public string Operation { get; set; }
        public string Table { get; set; }
        public string Column { get; set; }
        public string Description { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual AmbulanceCards AmbulanceCards { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
