//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbulanceCardPregnants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AmbulanceCardPregnants()
        {
            this.Pregnancies = new HashSet<Pregnancies>();
        }
    
        public int Id { get; set; }
        public string AbortionCount { get; set; }
        public string ChildbirthInThePeriodCount { get; set; }
        public string PrematureBirthCount { get; set; }
        public string ChildbirthPastDetails { get; set; }
        public string Heredity { get; set; }
        public string GynecologicalHistory { get; set; }
        public string SexuallyTransmittedDiseases { get; set; }
        public string ChronicDiseases { get; set; }
        public string PastSurgeries { get; set; }
        public string Hemotransfusion { get; set; }
        public string MenstrualFunction { get; set; }
        public string MenstruationDuration { get; set; }
        public string SexLife { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public string Contraception { get; set; }
        public string XRayFilePath { get; set; }
        public string HeredityHusband { get; set; }
        public string XRayHusbandFilePath { get; set; }
        public string PregnantCount { get; set; }
        public string ChildbirthCount { get; set; }
        public string SpontaneousAbortionsCount { get; set; }
        public string EctopicPregnancyCount { get; set; }
        public string Medobory { get; set; }
        public string FillNameHusband { get; set; }
        public string HusbandPhone { get; set; }
        public string BloodGroupHusband { get; set; }
        public string RHFactor { get; set; }
        public bool isPregnant { get; set; }
        public Nullable<System.DateTime> PregnancyStartTime { get; set; }
        public Nullable<int> ExtraGenitalDiseasesId { get; set; }
    
        public virtual AmbulanceCards AmbulanceCards { get; set; }
        public virtual ExtraGenitalDiseases ExtraGenitalDiseases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregnancies> Pregnancies { get; set; }
    }
}
