//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnosises()
        {
            this.MaintenanceClinicalExaminations = new HashSet<MaintenanceClinicalExaminations>();
            this.MaintenanceDiagnosis = new HashSet<MaintenanceDiagnosis>();
            this.MaintenanceHistoryDiagnosis = new HashSet<MaintenanceHistoryDiagnosis>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Id { get; set; }
        public int DiagnosisTypeId { get; set; }
        public string Code { get; set; }
        public string NameKZ { get; set; }
        public string NameRU { get; set; }
        public string NameEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceClinicalExaminations> MaintenanceClinicalExaminations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDiagnosis> MaintenanceDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceHistoryDiagnosis> MaintenanceHistoryDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
        public virtual DiagnosisTypes DiagnosisTypes { get; set; }
    }
}
