//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAnswerTemplates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentAnswerTemplates()
        {
            this.MaintenanceDocumentDetailAnswers = new HashSet<MaintenanceDocumentDetailAnswers>();
        }
    
        public int Id { get; set; }
        public int DocumentQuestionTemplateId { get; set; }
        public string Title { get; set; }
        public bool IsDeleted { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDocumentDetailAnswers> MaintenanceDocumentDetailAnswers { get; set; }
        public virtual DocumentQuestionTemplates DocumentQuestionTemplates { get; set; }
    }
}
