//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTemplates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentTemplates()
        {
            this.MaintenanceDocuments = new HashSet<MaintenanceDocuments>();
            this.DocumentQuestionTemplates = new HashSet<DocumentQuestionTemplates>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Title { get; set; }
        public Nullable<int> DocumentTemplateTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDocuments> MaintenanceDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentQuestionTemplates> DocumentQuestionTemplates { get; set; }
        public virtual DocumentTemplateType DocumentTemplateType { get; set; }
        public virtual Positions Positions { get; set; }
    }
}
