//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceDiagnosis
    {
        public int Id { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public int MaintenanceId { get; set; }
        public int DiagnosisId { get; set; }
        public Nullable<int> DiseasesCharacterId { get; set; }
    
        public virtual Maintenances Maintenances { get; set; }
        public virtual Diagnosises Diagnosises { get; set; }
        public virtual DiseasesCharacters DiseasesCharacters { get; set; }
    }
}
