//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceDiractions
    {
        public int Id { get; set; }
        public int MaintenanceId { get; set; }
        public Nullable<int> MaintenanceTypeId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> OrgUnitId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Maintenances Maintenances { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual MaintenanceTypes MaintenanceTypes { get; set; }
        public virtual OrgUnits OrgUnits { get; set; }
        public virtual Positions Positions { get; set; }
    }
}
