//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceStuffs
    {
        public int Id { get; set; }
        public int MaintenanceId { get; set; }
        public int StuffTypeId { get; set; }
        public string Path { get; set; }
        public string Title { get; set; }
        public string ResizedBase64 { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    
        public virtual Maintenances Maintenances { get; set; }
        public virtual StuffTypes StuffTypes { get; set; }
    }
}
