//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceMedicaments
    {
        public int Id { get; set; }
        public int MaintenanceId { get; set; }
        public int MedicamentId { get; set; }
        public string DayAmount { get; set; }
        public string Period { get; set; }
        public string TimeFrom { get; set; }
        public string TimeTo { get; set; }
        public System.DateTime Date { get; set; }
        public int OrgUnitId { get; set; }
    
        public virtual Maintenances Maintenances { get; set; }
        public virtual Medicaments Medicaments { get; set; }
        public virtual OrgUnits OrgUnits { get; set; }
    }
}
