//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceInjections
    {
        public int Id { get; set; }
        public int InjectionTypeId { get; set; }
        public int OrgUnitId { get; set; }
        public string DayAmount { get; set; }
        public string Period { get; set; }
        public int MaintenanceId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public string Comment { get; set; }
        public int StatusId { get; set; }
    
        public virtual Maintenances Maintenances { get; set; }
        public virtual InjectionTypes InjectionTypes { get; set; }
        public virtual OrgUnits OrgUnits { get; set; }
        public virtual TicketStatuses TicketStatuses { get; set; }
    }
}
