//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceDayHospitals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintenanceDayHospitals()
        {
            this.MaintenanceDayHospitalDates = new HashSet<MaintenanceDayHospitalDates>();
        }
    
        public int Id { get; set; }
        public int MaintenanceId { get; set; }
        public Nullable<int> DayHospitalTypeId { get; set; }
        public Nullable<float> Dosage { get; set; }
        public Nullable<int> OrgUnitId { get; set; }
        public Nullable<int> MaintenanceInjectionTypeId { get; set; }
        public Nullable<int> DosageTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDayHospitalDates> MaintenanceDayHospitalDates { get; set; }
        public virtual Maintenances Maintenances { get; set; }
        public virtual DayHospitalTypes DayHospitalTypes { get; set; }
        public virtual DosageTypes DosageTypes { get; set; }
        public virtual MaintenanceInjectionType MaintenanceInjectionType { get; set; }
        public virtual OrgUnits OrgUnits { get; set; }
    }
}
