//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceEveryYearDispancers
    {
        public int Id { get; set; }
        public int AmbulanceCardId { get; set; }
        public System.DateTime Date { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> DispancerReasonPetitionId { get; set; }
        public Nullable<int> DispancerDiagnosisDetailId { get; set; }
        public Nullable<int> DiagnosisTypeId { get; set; }
    
        public virtual AmbulanceCards AmbulanceCards { get; set; }
        public virtual DiagnosisTypes DiagnosisTypes { get; set; }
        public virtual DispancerDiagnosisDetails DispancerDiagnosisDetails { get; set; }
        public virtual DispancerReasonPetitions DispancerReasonPetitions { get; set; }
    }
}
