//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceDayHospitalDates
    {
        public int Id { get; set; }
        public int MaintenanceDayHospitalId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> IsFinished { get; set; }
    
        public virtual MaintenanceDayHospitals MaintenanceDayHospitals { get; set; }
    }
}
