//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceAnotherReasons
    {
        public int Id { get; set; }
        public Nullable<int> MaintenanceId { get; set; }
        public Nullable<int> ReasonPetitionId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Maintenances Maintenances { get; set; }
        public virtual ReasonPetitions ReasonPetitions { get; set; }
    }
}
