//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maintenances()
        {
            this.MaintenanceAnotherReasons = new HashSet<MaintenanceAnotherReasons>();
            this.MaintenanceClinicalExaminations = new HashSet<MaintenanceClinicalExaminations>();
            this.MaintenanceDayHospitals = new HashSet<MaintenanceDayHospitals>();
            this.MaintenanceDiagnosis = new HashSet<MaintenanceDiagnosis>();
            this.MaintenanceDiractions = new HashSet<MaintenanceDiractions>();
            this.MaintenanceDocuments = new HashSet<MaintenanceDocuments>();
            this.MaintenanceInjections = new HashSet<MaintenanceInjections>();
            this.MaintenanceMassages = new HashSet<MaintenanceMassages>();
            this.MaintenanceMedicaments = new HashSet<MaintenanceMedicaments>();
            this.MaintenanceProcedures = new HashSet<MaintenanceProcedures>();
            this.Maintenances1 = new HashSet<Maintenances>();
            this.MaintenanceStuffs = new HashSet<MaintenanceStuffs>();
        }
    
        public int Id { get; set; }
        public int AmbulanceCardId { get; set; }
        public int EmployeeId { get; set; }
        public int MaintenanceTypeId { get; set; }
        public int MaintenanceStatusId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> MaintenanceId { get; set; }
        public System.DateTime StartOn { get; set; }
        public Nullable<System.DateTime> FinishOn { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public bool IsPregnancy { get; set; }
        public bool IsDeleted { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    
        public virtual AmbulanceCards AmbulanceCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceAnotherReasons> MaintenanceAnotherReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceClinicalExaminations> MaintenanceClinicalExaminations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDayHospitals> MaintenanceDayHospitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDiagnosis> MaintenanceDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDiractions> MaintenanceDiractions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDocuments> MaintenanceDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceInjections> MaintenanceInjections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceMassages> MaintenanceMassages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceMedicaments> MaintenanceMedicaments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceProcedures> MaintenanceProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenances> Maintenances1 { get; set; }
        public virtual Maintenances Maintenances2 { get; set; }
        public virtual Tickets Tickets { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual MaintenanceStatuses MaintenanceStatuses { get; set; }
        public virtual MaintenanceTypes MaintenanceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceStuffs> MaintenanceStuffs { get; set; }
    }
}
