//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceDocuments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintenanceDocuments()
        {
            this.MaintenanceDocumentDetails = new HashSet<MaintenanceDocumentDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MaintenanceId { get; set; }
        public Nullable<int> DocumentTemplateId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDocumentDetails> MaintenanceDocumentDetails { get; set; }
        public virtual Maintenances Maintenances { get; set; }
        public virtual DocumentTemplates DocumentTemplates { get; set; }
    }
}
