//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyProcedures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotifyProcedures()
        {
            this.NotificationProcedures = new HashSet<NotificationProcedures>();
            this.NotifyProcedurePropertyTypes = new HashSet<NotifyProcedurePropertyTypes>();
            this.NotifyOperations = new HashSet<NotifyOperations>();
            this.Positions = new HashSet<Positions>();
        }
    
        public int Id { get; set; }
        public string Tilte { get; set; }
        public Nullable<int> NotifyPropertyTypeId { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public Nullable<int> NotifyProcedureTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationProcedures> NotificationProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotifyProcedurePropertyTypes> NotifyProcedurePropertyTypes { get; set; }
        public virtual NotifyProcedureTypes NotifyProcedureTypes { get; set; }
        public virtual NotifyPropertyTypes NotifyPropertyTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotifyOperations> NotifyOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Positions> Positions { get; set; }
    }
}
