//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyProcedurePropertyTypes
    {
        public int Id { get; set; }
        public Nullable<int> NotifyProcedureId { get; set; }
        public Nullable<int> NotifyPropertyTypeId { get; set; }
        public Nullable<bool> BooleanValue { get; set; }
        public Nullable<int> NumberValue { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual NotifyProcedures NotifyProcedures { get; set; }
        public virtual NotifyPropertyTypes NotifyPropertyTypes { get; set; }
    }
}
