//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationDetails
    {
        public int Id { get; set; }
        public Nullable<int> NotificationProcedureId { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<int> NotifyOperationId { get; set; }
    
        public virtual NotificationProcedures NotificationProcedures { get; set; }
        public virtual NotifyOperations NotifyOperations { get; set; }
    }
}
