//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationProcedures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificationProcedures()
        {
            this.NotificationDetails = new HashSet<NotificationDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> NotifyProcedureId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> NotifyStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationDetails> NotificationDetails { get; set; }
        public virtual NotifyProcedures NotifyProcedures { get; set; }
        public virtual NotifyStatus NotifyStatus { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
