//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgUnits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrgUnits()
        {
            this.MaintenanceDayHospitals = new HashSet<MaintenanceDayHospitals>();
            this.MaintenanceDiractions = new HashSet<MaintenanceDiractions>();
            this.MaintenanceInjections = new HashSet<MaintenanceInjections>();
            this.MaintenanceMassages = new HashSet<MaintenanceMassages>();
            this.MaintenanceMedicaments = new HashSet<MaintenanceMedicaments>();
            this.MaintenanceProcedures = new HashSet<MaintenanceProcedures>();
            this.Patients = new HashSet<Patients>();
            this.Employees = new HashSet<Employees>();
            this.OrgUnits1 = new HashSet<OrgUnits>();
            this.StaffLists = new HashSet<StaffLists>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int OrgUnitTypeId { get; set; }
        public Nullable<int> OrgUnitId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Weight { get; set; }
        public string GlobalEntityId { get; set; }
        public bool IsDeleted { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDayHospitals> MaintenanceDayHospitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceDiractions> MaintenanceDiractions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceInjections> MaintenanceInjections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceMassages> MaintenanceMassages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceMedicaments> MaintenanceMedicaments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceProcedures> MaintenanceProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patients> Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgUnits> OrgUnits1 { get; set; }
        public virtual OrgUnits OrgUnits2 { get; set; }
        public virtual OrgUnitTypes OrgUnitTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffLists> StaffLists { get; set; }
    }
}
