//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.NotificationProcedures = new HashSet<NotificationProcedures>();
            this.PatientAttachments = new HashSet<PatientAttachments>();
            this.Tickets = new HashSet<Tickets>();
            this.PatientAddresses = new HashSet<PatientAddresses>();
            this.Phones = new HashSet<Phones>();
            this.PatientLivingStatuses = new HashSet<PatientLivingStatuses>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PatientTypeId { get; set; }
        public int PatientStatusId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<bool> IsCanServicedAtHome { get; set; }
        public string Email { get; set; }
        public string ElectronicAgreementPath { get; set; }
        public string IIN { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> OrgUnitId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string GlobalEntityId { get; set; }
        public bool IsDeleted { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> CitizenshipId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string RpnUID { get; set; }
    
        public virtual AmbulanceCards AmbulanceCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationProcedures> NotificationProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAttachments> PatientAttachments { get; set; }
        public virtual Citizenship Citizenship { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Nationalities Nationalities { get; set; }
        public virtual OrgUnits OrgUnits { get; set; }
        public virtual PatientStatuses PatientStatuses { get; set; }
        public virtual PatientTypes PatientTypes { get; set; }
        public virtual Priorities Priorities { get; set; }
        public virtual Sectors Sectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAddresses> PatientAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phones> Phones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientLivingStatuses> PatientLivingStatuses { get; set; }
    }
}
