//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregnancies
    {
        public int Id { get; set; }
        public int AmbulanceCardPregnantId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Period { get; set; }
        public string Status { get; set; }
        public int GenderId { get; set; }
        public float Weight { get; set; }
        public float Height { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Maternity { get; set; }
    
        public virtual AmbulanceCardPregnants AmbulanceCardPregnants { get; set; }
        public virtual Areas Areas { get; set; }
        public virtual Genders Genders { get; set; }
    }
}
