//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRoomBreaks
    {
        public int Id { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public int TypeId { get; set; }
        public int StaffRoomId { get; set; }
    
        public virtual StaffRoomBreakTypes StaffRoomBreakTypes { get; set; }
        public virtual StaffRooms StaffRooms { get; set; }
    }
}
