//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffLists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffLists()
        {
            this.EmployeeLeaves = new HashSet<EmployeeLeaves>();
            this.WorkSchedules = new HashSet<WorkSchedules>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int OrgUnitId { get; set; }
        public int PositionId { get; set; }
        public bool IsSelfRecording { get; set; }
        public bool IsRecording { get; set; }
        public Nullable<double> AdmissionDuration { get; set; }
        public Nullable<int> StaffRoomId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<double> Salary { get; set; }
        public bool IsMain { get; set; }
        public bool IsDeleted { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual OrgUnits OrgUnits { get; set; }
        public virtual Positions Positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeaves> EmployeeLeaves { get; set; }
        public virtual Sectors Sectors { get; set; }
        public virtual StaffRooms StaffRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSchedules> WorkSchedules { get; set; }
    }
}
