//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoveData.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSchedules
    {
        public int Id { get; set; }
        public byte WeekDay { get; set; }
        public bool IsMain { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public bool IsFilter { get; set; }
        public bool IsActive { get; set; }
        public int StaffListId { get; set; }
    
        public virtual StaffLists StaffLists { get; set; }
    }
}
