//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationProj.PatientRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbulanceCards
    {
        public int Id { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public string WorkPlace { get; set; }
        public Nullable<int> BloodGruopId { get; set; }
        public Nullable<int> RhFactorId { get; set; }
        public Nullable<System.DateTime> DischargeFromHospitalDate { get; set; }
        public string Hospital { get; set; }
        public string AllergicHistory { get; set; }
        public string EpidemiologicalHistory { get; set; }
        public string ReactionsFromMedicaments { get; set; }
        public string IndividualCharacteristics { get; set; }
        public string SpecialCases { get; set; }
        public string SmokingInfo { get; set; }
        public string DrinkInfo { get; set; }
        public Nullable<int> WorkSpecialityId { get; set; }
        public string PatientPosition { get; set; }
        public string SocialStatus { get; set; }
        public Nullable<int> BloodGroup_Id { get; set; }
        public bool IsDeleted { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public Nullable<System.DateTime> PolyclinicJoiningDate { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
