//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationProj.PatientRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public int Id { get; set; }
        public Nullable<int> PatientTypeId { get; set; }
        public int PatientStatusId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<bool> IsCanServicedAtHome { get; set; }
        public string Email { get; set; }
        public string ElectronicAgreementPath { get; set; }
        public string IIN { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> OrgUnitId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string GlobalEntityId { get; set; }
        public bool IsDeleted { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> CitizenshipId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string RpnUID { get; set; }
    
        public virtual AmbulanceCards AmbulanceCards { get; set; }
        public virtual Sectors Sectors { get; set; }
    }
}
